title:              LINJE Iman
email:              linjevetcoder01@gmail.com
description:        My Personal Website
author:             Iman Linje
baseurl:            "/Iman-L.github.io"
url:                "linjeiman.me"

# Social Profiles
twitter_username:   
github_username:    Iman Linje
facebook_username:  
instagram_username:  
linkedin_username: Iman Linje

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
